CREATE USER "RMANBACKUP" IDENTIFIED BY "ja8shd7d" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";
GRANT 	UNLIMITED TABLESPACE 	TO "RMANBACKUP";
GRANT 	CREATE SESSION 			TO "RMANBACKUP";
GRANT 	DBA 					TO "RMANBACKUP";
GRANT 	SELECT_CATALOG_ROLE 	TO "RMANBACKUP";
GRANT 	SYSDBA 					TO "RMANBACKUP";
SELECT NAME, DBID FROM V$DATABASE;

